"""empty message

Revision ID: 466279c65abd
Revises: 8a194178f250
Create Date: 2023-08-11 15:46:11.815521

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '466279c65abd'
down_revision = '8a194178f250'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prg', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Prg', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Prg', type_='foreignkey')
    op.drop_column('Prg', 'user_id')
    # ### end Alembic commands ###
