"""empty message

Revision ID: 25ea6a467e37
Revises: f2da805e9817
Create Date: 2023-09-29 08:09:29.651091

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea6a467e37'
down_revision = 'f2da805e9817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Note_geom', table_name='Note', postgresql_using='gist')
    # ### end Alembic commands ###
