"""empty message

Revision ID: 866e08f27434
Revises: f87031a2f07f
Create Date: 2023-08-12 11:52:13.490762

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import geoalchemy2 # added
from app.schemas.common_schema import IParticelleLivelloEnum # added


# revision identifiers, used by Alembic.
revision = '866e08f27434'
down_revision = 'f87031a2f07f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Particelle',
    sa.Column('livello', sqlalchemy_utils.types.choice.ChoiceType(IParticelleLivelloEnum), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('comune', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sezione', sa.Integer(), nullable=True),
    sa.Column('foglio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allegato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sviluppo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_Particelle_geom', 'Particelle', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_Particelle_id'), 'Particelle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Particelle_id'), table_name='Particelle')
    op.drop_index('idx_Particelle_geom', table_name='Particelle', postgresql_using='gist')
    op.drop_table('Particelle')
    # ### end Alembic commands ###
