"""empty message

Revision ID: 8a194178f250
Revises: 10f8a5e2e923
Create Date: 2023-08-11 15:28:24.181907

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.schemas.common_schema import IPrgStatusEnum, IPrgTypeEnum
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '8a194178f250'
down_revision = '10f8a5e2e923'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prg', sa.Column('land_type', sqlalchemy_utils.types.choice.ChoiceType(IPrgTypeEnum), nullable=True))
    op.alter_column('Prg', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Prg', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Prg', 'land_type')
    # ### end Alembic commands ###
