"""empty message

Revision ID: f87031a2f07f
Revises: 466279c65abd
Create Date: 2023-08-12 11:36:14.119695

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.schemas.common_schema import IPrgTypeEnum
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f87031a2f07f'
down_revision = '466279c65abd'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prg', sa.Column('zona', sqlalchemy_utils.types.choice.ChoiceType(IPrgTypeEnum), nullable=True))
    op.add_column('Prg', sa.Column('db_id', sa.Integer(), nullable=False))
    op.add_column('Prg', sa.Column('area', sa.Integer(), nullable=False))
    op.add_column('Prg', sa.Column('frazione', sa.Integer(), nullable=False))
    op.add_column('Prg', sa.Column('id_area', sa.Integer(), nullable=False))
    op.add_column('Prg', sa.Column('articolo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Prg', sa.Column('comparto', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Prg', sa.Column('scheda', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Prg', sa.Column('proprieta', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Prg', sa.Column('sul', sa.Integer(), nullable=False))
    op.add_column('Prg', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('Prg', 'land_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prg', sa.Column('land_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('Prg', 'end_date')
    op.drop_column('Prg', 'sul')
    op.drop_column('Prg', 'proprieta')
    op.drop_column('Prg', 'scheda')
    op.drop_column('Prg', 'comparto')
    op.drop_column('Prg', 'articolo')
    op.drop_column('Prg', 'id_area')
    op.drop_column('Prg', 'frazione')
    op.drop_column('Prg', 'area')
    op.drop_column('Prg', 'db_id')
    op.drop_column('Prg', 'zona')
    # ### end Alembic commands ###
